 (line: 4) - APPLICATION:__APP_ID__ [Mar/03/15:15:29:12] - Request was brought back with error => {"category":"authorization","code":"access-denied","message":"The authenticated user does not have sufficient permissions to access this resource","details":[{"name":"requestMethod","value":"GET"},{"name":"remoteAddress","value":"127.0.0.1"},{"name":"requestPath","value":"\/users\/u-mmuxnl7o2u2ijsdg2hrwdsq\/account"}]}
 (line: 4) - APPLICATION: [Mar/03/15:15:29:12] - Request was brought back with error => {"category":"authorization","code":"access-denied","message":"The authenticated user does not have sufficient permissions to access this resource","details":[{"name":"requestMethod","value":"GET"},{"name":"remoteAddress","value":"127.0.0.1"},{"name":"requestPath","value":"\/users\/phoneNumbers"}]}
